### ISSUE TITLE
Crashing with Music Import

### ISSUE THREAD

**Issue by dmanlfc** [artemanufrij/playmymusic#33]
The only log information I have is as such...

Track ID: 4866 - Only You
Track ID: 4867 - Out On The Fields
Segmentation fault (core dumped)

**Comment by artemanufrij** [comment]
Crashes it all the time on same track?

**Comment by artemanufrij** [comment]
@dmanlfc have you your library local or mounted from like a samba share?

**Comment by dmanlfc** [comment]
@artemanufrij NFS share off my NAS box.
Just running another import & so far so good.

**Comment by artemanufrij** [comment]
@dmanlfc thanks for your feedback. I will setup a NFS share on my server. I tested it only with samba yet.

**Comment by dmanlfc** [comment]
Just crashed again - another random place...

Track ID: 5648 - Blue Ocean Floor
Track ID: 5649 - New Moon (The Meadow)
ARTIST ID: 89ad4ac3-39f7-470e-963a-56509c546377 (Massive R&B - Spring Collection 2008 / Various Artists)
ARTIST ID: 89ad4ac3-39f7-470e-963a-56509c546377 (Now 69 / Various Artists)
Segmentation fault (core dumped)

**Comment by artemanufrij** [comment]
OK, I have to find out is it a NFS or an otherone issue.

**Comment by dmanlfc** [comment]
And again now...

ARTIST ID: d87e52c5-bb8d-4da8-b941-9f4928627dc8 (ABBA Gold: Greatest Hits / ABBA)

** (com.github.artemanufrij.playmymusic:2715): WARNING **: MusicBrainzManager.vala:247: Image file '/home/daniel/.cache/1733484816.jpg' contains no data
ARTIST ID: 8ef1df30-ae4f-4dbd-9351-1a32b208a01e (Songs in A Minor / Alicia Keys)
ARTIST ID: 28cbf94d-0700-4095-a188-37e373b069a7 (Kish Kash / Basement Jaxx)
Track ID: 5650 - Not Over Yet (f. Danielle)
Track ID: 5651 - Superman (Dancing DJ'S Remix)
ARTIST ID: d9c9cfb7-f751-4fb0-97c0-b3ddd768bc78 (Greatest Hits / Bell Biv Devoe)
Track ID: 5652 - It's Over Now (Hardino Remix) (f. Siobhan)
Track ID: 5653 - Shut Up copy 000
ARTIST ID: 05071a7e-e71c-4306-a509-591cd3686893 (We Don't Need To Whisper / Angels & Airwaves)
Track ID: 5654 - Nasty Girl (Riffs & Rays Remix)
ARTIST ID: 05071a7e-e71c-4306-a509-591cd3686893 (I-Empire / Angels & Airwaves)
Track ID: 5655 - Too Lost In You
Track ID: 5656 - We Belong Together
ARTIST ID: 05071a7e-e71c-4306-a509-591cd3686893 (Love / Angels & Airwaves)
Track ID: 5657 - Family Affair
Track ID: 5658 - You
ARTIST ID: ba853904-ae25-4ebb-89d6-c44cfbd71bd2 (The Best Of Blur / Blur)
Track ID: 5659 - Me & U
ARTIST ID: 060e47de-6ce8-4954-808a-689ac685c28d (Blast Off! - Part 1 / Bolt Action)
Track ID: 5660 - Ma Ma Ma Belle (7' Edit)
Track ID: 5661 - Four Little Diamonds
ARTIST ID: b41b38d4-ef3e-4f37-8c75-cfe9af999696 (Cage The Elephant / Cage The Elephant)
Track ID: 5662 - On A Ragga Tip (Original Mix)
ARTIST ID: 4b1bf05d-0e3c-44a3-9fc8-ad088fc25797 (Buckingham Nicks / Buckingham Nicks)
Segmentation fault (core dumped)

**Comment by artemanufrij** [comment]
@dmanlfc could you test current master branch please?

**Comment by dmanlfc** [comment]
@artemanufrij - sorry but the same again within 30 seconds

ARTIST ID: d87e52c5-bb8d-4da8-b941-9f4928627dc8 (ABBA Gold: Greatest Hits / ABBA)
ARTIST ID: 8ef1df30-ae4f-4dbd-9351-1a32b208a01e (Songs in A Minor / Alicia Keys)
ARTIST ID: a874bf2c-8697-417e-b9e3-2f93c7ca9000 (2004 Mixes / DJ Marathon Man)
ARTIST ID: a874bf2c-8697-417e-b9e3-2f93c7ca9000 (Marathon Man 2015 Mixes / DJ Marathon Man)
ARTIST ID: 28cbf94d-0700-4095-a188-37e373b069a7 (Kish Kash / Basement Jaxx)
Track ID: 7347 - God Save the Queen
ARTIST ID: d9c9cfb7-f751-4fb0-97c0-b3ddd768bc78 (Greatest Hits / Bell Biv Devoe)
ARTIST ID: 1a989060-1abb-4e08-a1f2-20179c6f7315 (Box O' Bangers 2016 / Dj Marathon Man)
Track ID: 7348 - When Will I See You Again
Track ID: 7349 - Baby Be Mine
ARTIST ID: 060e47de-6ce8-4954-808a-689ac685c28d (Blast Off! - Part 1 / Bolt Action)
ARTIST ID: b41b38d4-ef3e-4f37-8c75-cfe9af999696 (Cage The Elephant / Cage The Elephant)
Segmentation fault (core dumped)

**Comment by artemanufrij** [comment]
@dmanlfc and now?

**Comment by dmanlfc** [comment]
@artemanufrij nope :-(

Album ID: 422
Track ID: 7577 - Tell Me
ARTIST ID: 1a989060-1abb-4e08-a1f2-20179c6f7315 (Box O' Bangers 2016 / Dj Marathon Man)
Track ID: 7578 - I'm Gonna Be (500 Miles)
ARTIST ID: 2c4dae8c-e591-49e0-9c5a-62b310a15788 (Rockferry / Duffy)
Track ID: 7579 - Moving On Up
ARTIST ID: 4a5777b3-f55b-437c-8b23-d9ee7791c7fc (Desireless / Eagle-Eye Cherry)
ARTIST ID: c3009d7a-51ac-4c9c-888a-04f5c3c4be0c (Eazy-Duz-It / Eazy-E)
Track ID: 7580 - American Pie
ARTIST ID: 7cfaac66-62e5-4fcd-af1b-9d3aa8f68e8b (Our Version Of Events / Emeli Sande)
Segmentation fault (core dumped)

**Comment by artemanufrij** [comment]
@dmanlfc you pulled now version?

**Comment by dmanlfc** [comment]
@artemanufrij yes I just rebuilt it

**Comment by artemanufrij** [comment]
fuck, I can't reproduce it.... I tryed it >10 times without problems and I have > 5500 files in my library...

**Comment by artemanufrij** [comment]
I will setup a NFS network tomorrow...

**Comment by dmanlfc** [comment]
Sorry :-) Older builds worked fine. We need to find the trigger - either my files or a lookup DB import bug.
Some artists in my library won't be on MusicBrainz as they're mine or my sons music.

**Comment by artemanufrij** [comment]
May be MusicBrainz interface is the reason...

**Comment by dmanlfc** [comment]
Dunno - maybe throw some extra logging in there?
I will try another laptop or two also with the new build at some point today - same library

**Comment by artemanufrij** [comment]
@dmanlfc It would be very helpful!!! Thank you!

**Comment by artemanufrij** [comment]
Hey @dmanlfc,

I tested it over NFS. It works also without problems on my system. :confused: 

New master branch has a new option for enable/disable musicbrainz requests. Could you test it please? But you should install new version on your system `sudo make install` because I added a new property into schema.

1. disable all switsches
2. restart application
3. rescan library

![bildschirmfoto von 2017-10-30 11 18 40](https://user-images.githubusercontent.com/16517095/32165824-52b6204e-bd64-11e7-93f9-2cf5f2383d3f.png)

**Comment by artemanufrij** [comment]
@dmanlfc 
What I found out:

**Samba**:
Connected via `LAN`: works
Connected via `WiFi`: works

**NFS**:
Connected via `LAN`: works (ot: much faster as Samba)
Connected voa `WiFi`: crashes each ~ 30 seconds

**Comment by dmanlfc** [comment]
@artemanufrij - Confirmed WiFi here also - extremely weird.

**Comment by artemanufrij** [comment]
@dmanlfc I don't have an idea how it can be fixed. :confused:

**Comment by artemanufrij** [comment]
@dmanlfc so now it works here... could you verify it please?

**Comment by dmanlfc** [comment]
@artemanufrij - yes just testing now. WiFi seems terrible but LAN provides stability.
I reset the views and I'm currently importing the Library again. Fine on Gigabit :-)

**Comment by artemanufrij** [comment]
pull last master... I fixed it on WiFi

**Comment by dmanlfc** [comment]
@artemanufrij - it's certainly better but it did crash a few times. Although not as often as before.
Off to bed here but certainly a bit more robust.
LAN - no issues at all.

**Comment by artemanufrij** [comment]
Thank you for your support!

**Comment by artemanufrij** [comment]
@dmanlfc I can't reproduce this bug any more. I tested it on three systems more than 20 times. Can we close this issue?

**Comment by dmanlfc** [comment]
@artemanufrij currently all three laptops still crash over WiFi here. Even with MusicBrainz turned off.
One Laptop has the current App Centre build (not depicted below).
I never had the problem with older builds from memory. Maybe the problem manifested around the 0.1.6 build...

Example of Artist fetching on & off with git build...

daniel@daniel-Latitude-E4310:~$ com.github.artemanufrij.playmymusic
ARTIST ID: 8ef1df30-ae4f-4dbd-9351-1a32b208a01e (Songs in A minor / Alicia Keys)
ARTIST ID: 05071a7e-e71c-4306-a509-591cd3686893 (We Don't Need To Whisper / Angels & Airwaves)
ARTIST ID: 05071a7e-e71c-4306-a509-591cd3686893 (I-Empire / Angels & Airwaves)
ARTIST ID: 05071a7e-e71c-4306-a509-591cd3686893 (Love / Angels & Airwaves)
ARTIST ID: ba853904-ae25-4ebb-89d6-c44cfbd71bd2 (The Best Of Blur / Blur)
ARTIST ID: 060e47de-6ce8-4954-808a-689ac685c28d (Blast Off! - Part 1 / Bolt Action)
ARTIST ID: a874bf2c-8697-417e-b9e3-2f93c7ca9000 (2004 Mixes / DJ Marathon Man)
ARTIST ID: a874bf2c-8697-417e-b9e3-2f93c7ca9000 (Marathon Man 2015 Mixes / DJ Marathon Man)
Segmentation fault (core dumped)
daniel@daniel-Latitude-E4310:~$ com.github.artemanufrij.playmymusic
Track ID: 6702 - Cops & Robbers
Segmentation fault (core dumped)
daniel@daniel-Latitude-E4310:~$ com.github.artemanufrij.playmymusic
Track ID: 6703 - Singin' In The Rain
Segmentation fault (core dumped)

**Comment by dmanlfc** [comment]
@artemanufrij Here on Gigabit Ethernet (logs below) - everything runs fine & fast.
Note: The parallel track imports due to speed & obviously multi threaded fetching. 
With WiFi this is always a serial track import. Do you think something may be timing out?
Are the tracks read into a memory buffer & flushing too quickly? (clutching at straws here now :-))

Track ID: 8541 - If You Leave Me Now
Track ID: 8542 - Smoke On The Water
Track ID: 8544 - Youre All I Have
Track ID: 8534 - One Time
Track ID: 8539 - Locked Up
Track ID: 8535 - If You Come To Me
Track ID: 8431 - Why
Track ID: 8467 - Whole Lotta Shakin' Going On
Track ID: 8540 - Dancing With Myself
Track ID: 8394 - Lucy In The Sky With Diamonds
Track ID: 8515 - Gangstas Paradise
Track ID: 8472 - Love On My Mind
Track ID: 8445 - Respect
Track ID: 8546 - Eight Miles High
Track ID: 8543 - Dead Ringer For Love
Track ID: 8451 - Ride
Track ID: 8533 - Hooked On Classics
Track ID: 8312 - Back From Outta Space (Flower Power Remix)
Track ID: 8326 - Shy Guy
Track ID: 8545 - Someday
Track ID: 8362 - Mellow Yellow
Track ID: 8548 - Make Me Smile (Come Up And See Me)
Track ID: 8501 - Hold Your Head Up Hi
Track ID: 8550 - Blitzkrieg Bop
Track ID: 8549 - Stayin' Alive
Track ID: 8547 - Cat Scratch Fever
Track ID: 8551 - Lady Marmalade
Track ID: 8527 - Solar Midnite
Track ID: 8553 - Kung Fu Fighting
Track ID: 8552 - Rock On

**Comment by artemanufrij** [comment]
@dmanlfc crashes it on track id ca. > 6000?

**Comment by dmanlfc** [comment]
@artemanufrij over > 2-3000 I see it manifest. It does get worse > 6000 for sure.
I will test the new the latest build with the disposal code later tonight :-)

**Comment by dmanlfc** [comment]
OK latest build is MUCH better!
It only crashed twice in over 8,500 songs! :+1:

**Comment by artemanufrij** [comment]
@dmanlfc I found some file objects. I added a .dispose ().  Could you test it again please?

**Comment by dmanlfc** [comment]
@artemanufrij sorry still a problem :-(
Crashed at track 2901 & then again at 3188...
